### ISSUE TITLE
UnicodeEncodeError: crash when downloading repositories with unicode name

### ISSUE THREAD

**Issue by facconi** [samkuehn/bitbucket-backup#35]
```
Traceback (most recent call last):
  File "~/bitbucket-backup/backup.py", line 172, in main
    debug("Backing up [%s]..." % repo.get("name"), True)
  File "~/bitbucket-backup/backup.py", line 27, in debug
    print("{0} - {1}".format(datetime.datetime.now(), message))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe0' in 
        position 19: ordinal not in range(128)
Unknown error. (11)
```

**Comment by samkuehn** [comment]
This should be fixed with a9c2bb18346b92ddcdd1d441ad413cf2c2ac9eab
