### ISSUE TITLE
Not Working with python 2 or 3 and other things 

### ISSUE THREAD

**Issue by pserrano** [samkuehn/bitbucket-backup#36]
Hi! 

When i use your app like this:  

```bash
bitbucket-backup -u blabla -l ~/utils/bitbucket-backup -c --mirror --with-wiki -t company -v
 ```
i see this error on my shell 
```bash
Traceback (most recent call last):
  File "/usr/bin/backup.py", line 175, in main
    clone_repo(repo, backup_dir, http, username, password, mirror=_mirror, with_wiki=_with_wiki)
  File "/usr/bin/backup.py", line 77, in clone_repo
    owner_url = urllib.quote(owner)
AttributeError: 'module' object has no attribute 'quote'
```
I have a arch linux and 

```bash
python -V                                                                                        
Python 3.4.3
```
i've test with python 2 and obtain same error.

**Comment by samkuehn** [comment]
I was able to replicate and fix this in python 3.  Could not replicate the issue in python 2.
