### ISSUE TITLE
[SSL: CERTIFICATE_VERIFY_FAILED] error

### ISSUE THREAD

**Issue by millerjira** [samkuehn/bitbucket-backup#50]
Hello,

When Im trying to run the:

pip install https://github.com/samkuehn/bitbucket-backup/archive/master.zip
(Python verion: Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55)
I'm getting the following error:

C:\>pip install https://github.com/samkuehn/bitbucket-backup/archive/master.zip
Collecting https://github.com/samkuehn/bitbucket-backup/archive/master.zip
Exception:
Traceback (most recent call last):
  File "c:\users\user-1\appdata\local\programs\python\python35\lib\site-packages\pip\_vendor\requests\packages\urllib
3\connectionpool.py", line 559, in urlopen
    body=body, headers=headers)
  File "c:\users\user-1\appdata\local\programs\python\python35\lib\site-packages\pip\_vendor\requests\packages\urllib
3\connectionpool.py", line 345, in _make_request
    self._validate_conn(conn)
  File "c:\users\user-1\appdata\local\programs\python\python35\lib\site-packages\pip\_vendor\requests\packages\urllib
3\connectionpool.py", line 784, in _validate_conn
    conn.connect()
  File "c:\users\user-1\appdata\local\programs\python\python35\lib\site-packages\pip\_vendor\requests\packages\urllib
3\connection.py", line 252, in connect
    ssl_version=resolved_ssl_version)
  File "c:\users\user-1\appdata\local\programs\python\python35\lib\site-packages\pip\_vendor\requests\packages\urllib
3\util\ssl_.py", line 305, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "c:\users\user-1\appdata\local\programs\python\python35\lib\ssl.py", line 377, in wrap_socket
    _context=self)
  File "c:\users\user-1\appdata\local\programs\python\python35\lib\ssl.py", line 752, in __init__
    self.do_handshake()
  File "c:\users\user-1\appdata\local\programs\python\python35\lib\ssl.py", line 988, in do_handshake
    self._sslobj.do_handshake()
  File "c:\users\user-1\appdata\local\programs\python\python35\lib\ssl.py", line 633, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\user-1\appdata\local\programs\python\python35\lib\site-packages\pip\_vendor\requests\adapters.py", l
ine 376, in send
    timeout=timeout
  File "c:\users\user-1\appdata\local\programs\python\python35\lib\site-packages\pip\_vendor\requests\packages\urllib
3\connectionpool.py", line 588, in urlopen
    raise SSLError(e)
pip._vendor.requests.packages.urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_
ssl.c:645)
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\user-1\appdata\local\programs\python\python35\lib\site-packages\pip\basecommand.py", line 209, in ma
in
    status = self.run(options, args)
  File "c:\users\user-1\appdata\local\programs\python\python35\lib\site-packages\pip\commands\install.py", line 299,
in run
    requirement_set.prepare_files(finder)
  File "c:\users\user-1\appdata\local\programs\python\python35\lib\site-packages\pip\req\req_set.py", line 360, in pr
epare_files
    ignore_dependencies=self.ignore_dependencies))
  File "c:\users\user-1\appdata\local\programs\python\python35\lib\site-packages\pip\req\req_set.py", line 577, in _p
repare_file
    session=self.session, hashes=hashes)
  File "c:\users\user-1\appdata\local\programs\python\python35\lib\site-packages\pip\download.py", line 810, in unpac
k_url
    hashes=hashes
  File "c:\users\user-1\appdata\local\programs\python\python35\lib\site-packages\pip\download.py", line 649, in unpac
k_http_url
    hashes)
  File "c:\users\user-1\appdata\local\programs\python\python35\lib\site-packages\pip\download.py", line 842, in _down
load_http_url
    stream=True,
  File "c:\users\user-1\appdata\local\programs\python\python35\lib\site-packages\pip\_vendor\requests\sessions.py", l
ine 480, in get
    return self.request('GET', url, **kwargs)
  File "c:\users\user-1\appdata\local\programs\python\python35\lib\site-packages\pip\download.py", line 378, in reque
st
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "c:\users\user-1\appdata\local\programs\python\python35\lib\site-packages\pip\_vendor\requests\sessions.py", l
ine 468, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\users\user-1\appdata\local\programs\python\python35\lib\site-packages\pip\_vendor\requests\sessions.py", l
ine 576, in send
    r = adapter.send(request, **kwargs)
  File "c:\users\user-1\appdata\local\programs\python\python35\lib\site-packages\pip\_vendor\cachecontrol\adapter.py"
, line 46, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "c:\users\user-1\appdata\local\programs\python\python35\lib\site-packages\pip\_vendor\requests\adapters.py", l
ine 447, in send
    raise SSLError(e, request=request)
pip._vendor.requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate veri

**Comment by samkuehn** [comment]
Unfortunately I am unable to replicate this error.  It appears you are using Windows and I am not a Windows user.
