### ISSUE TITLE
urlopen().read() return bytes, needs decode?

### ISSUE THREAD

**Issue by pere3** [samkuehn/bitbucket-backup#59]
```
Traceback (most recent call last):
  File "/opt/bitbucket-backup/env/bin/backup.py", line 313, in main
    repos = get_repositories(username=username, password=password, team=team)
  File "/opt/bitbucket-backup/env/bin/backup.py", line 127, in get_repositories
    repos_data = json.loads(result)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
Unknown error. (11)
```

fixed with:
```
result = urlopen(request).read().decode('utf-8')
```

**Comment by samkuehn** [comment]
Complete.  Thanks @pere3.

**Comment by pere3** [comment]
there is also need for .decode() inside while loop for pagination:

```
while repos_data.get("next"):
        request = Request(repos_data.get("next"), data, header)
        result = urlopen(request).read()
        repos_data = json.loads(result)
```
